"""Pipeline state schema — shared across all agent nodes."""

from __future__ import annotations

from typing import Any

from typing_extensions import TypedDict


class SentinelState(TypedDict, total=False):
    """Shared state for the Sentinel earnings-analysis pipeline.

    Each agent node reads from and writes to this state.
    Fields use ``total=False`` so nodes can return partial updates.
    """

    ticker: str
    """Company ticker symbol (e.g. ``"AAPL"``)."""

    raw_data: dict[str, Any]
    """Structured financial data extracted by the Research agent."""

    model_yaml: str
    """Forge YAML model generated by the Modeler agent."""

    forge_results: dict[str, Any]
    """Calculation results from Forge (deterministic numbers)."""

    brief: str
    """Executive brief produced by the Synthesizer agent."""

    quick: bool
    """When True, skip Risk Analyst and Scenario Planner nodes."""

    risk_analysis: dict[str, Any]
    """Monte Carlo simulation, tornado sensitivity, and break-even results."""

    scenario_analysis: dict[str, Any]
    """Bull / Base / Bear scenario projection results."""

    historical_context: list[dict[str, Any]]
    """Historical earnings records retrieved from Qdrant for trend analysis.

    Each element is a payload dict from a past quarter's earnings record
    (ticker, period, revenue, margins, etc.).  Empty list when no history
    is available (first run or Qdrant unavailable).
    """

    analyst_feedback: str
    """Analyst feedback injected before the Synthesizer re-runs.

    Set when the analyst rejects the draft analysis during the HITL approval
    gate (``--hitl`` mode).  Empty string when no feedback was provided.
    The Synthesizer incorporates this feedback if present.
    """
