"""Pipeline state schema — shared across all agent nodes."""

from __future__ import annotations

from typing import Any

from typing_extensions import TypedDict


class SentinelState(TypedDict, total=False):
    """Shared state for the Sentinel earnings-analysis pipeline.

    Each agent node reads from and writes to this state.
    Fields use ``total=False`` so nodes can return partial updates.
    """

    ticker: str
    """Company ticker symbol (e.g. ``"AAPL"``)."""

    raw_data: dict[str, Any]
    """Structured financial data extracted by the Research agent."""

    model_yaml: str
    """Forge YAML model generated by the Modeler agent."""

    forge_results: dict[str, Any]
    """Calculation results from Forge (deterministic numbers)."""

    brief: str
    """Executive brief produced by the Synthesizer agent."""
